CC=gcc
FLAG= -Wall -g -O0 -lm
OBJ= Test.c ../lib/io.o ../lib/graph.o ../lib/stack.o ../lib/set.o ../lib/connected.o ../lib/color.o ../lib/ACM.o ../lib/eulerian.o ../lib/cloud.o

test.exe: $(OBJ)
	gcc $(FLAG) $^ -o $@ 
